//! Real-renderer panel snapshots — ui-quality-gate-overhaul M1-B +
//! ui-test-harness-viewport-matrix v0.1.0.
//!
//! ## Viewport matrix (ui-test-harness-viewport-matrix v0.1.0)
//!
//! Previously this file used a single `("typical", (1280, 720), 1.0)` slot
//! (the M1-B PoC viewport). With the viewport-matrix expansion each of the
//! 7 fixtures now runs at all three operator-locked slots via
//! `viewport_matrix::snapshot_widget_at_slot`.
//!
//! Per D-VPM-3 subtlety: the M1-B PoC "typical" was 1280×720, NOT the
//! matrix `typical` 1920×1080. The old typical baselines stay under their
//! current filenames (`*_dark_typical.png` at 1280×720) for the 2 stable
//! fixtures; the new `__floor`, `__typical`, `__operator` matrix baselines
//! use the viewport_matrix SLOTS convention (floor=1280×720,
//! typical=1920×1080, operator=3360×1890×2.0).
//!
//! ## Baseline path convention (render_snapshots subdir)
//!
//! ```text
//! crates/ui/tests/visual-baselines/render_snapshots/<fixture_name>__<slot_name>.png
//! ```
//!
//! Note: the existing M1-B baselines (`chart_screen_dark_typical.png`,
//! `strategies_ready_dark_typical.png`) are NOT renamed — they live at
//! the old path and are exercised by the renamed `run_panel_slot_legacy`
//! helper. The new matrix expansion writes NEW files alongside them.
//!
//! ## First-run semantics
//!
//! `viewport_matrix::snapshot_widget_at_slot` auto-writes the baseline on
//! first run when it doesn't exist. The orchestrator owns the capture-and-
//! commit cycle.
//!
//! ## Opt-outs (D-VPM-4)
//!
//! None for this file — all 5 `#[ignore]`d tests stay `#[ignore]`d and get
//! matrix expansion too (the `#[ignore]` decorator carries through per D-VPM-3).
//!
//! ## SSIM threshold (per architect Q5)
//!
//! `SSIM_THRESHOLD = 0.99` strict, **no epsilon band**. Same contract as M1-B.

// cockpit-cross-platform ADR-0057 D2: visual baselines are macOS-canonical.
// On Linux/Windows cosmic-text resolves body text via PlatformFallback against
// the per-OS system font DB, producing different glyph rasterization — these
// tests would not match the macOS-captured PNGs. Gate the entire file to
// compile only on macOS; on Linux/Windows the file compiles to nothing (tests
// are skipped, never re-baselined). See ADR-0057 D2 and the runbook.
#![cfg(target_os = "macos")]
#![allow(clippy::expect_used, clippy::unwrap_used)]
// The viewport-matrix slot test fn names use double-underscore separators
// that match the baseline PNG filenames exactly (e.g. `strategies_ready__floor`).
// Suppressing the non_snake_case lint is the lowest-noise approach — renaming
// would de-sync fn names from baselines.
#![allow(non_snake_case)]

use std::time::Duration;

#[path = "fixtures/mod.rs"]
mod fixtures;

use fixtures::viewport_matrix;
use fixtures::visual_diff::matches_screenshot;
use ui::test_support::program_from_cockpit;

/// SSIM threshold — strict 0.99 per architect Q5 resolution
/// (`spec/v1/ui-quality-gate-overhaul/feature.md ## Q5`). The helper at
/// `fixtures/visual_diff.rs` currently does byte-strict compare; an SSIM
/// fallback path is queued as a follow-up (see "Open questions" in the
/// developer's handoff envelope). The threshold is the architectural
/// target — the constant ships here so the SSIM-fallback path lands on
/// a stable acceptance criterion when it materialises.
#[allow(dead_code)]
pub const SSIM_THRESHOLD: f64 = 0.99_f64;

/// Process-wide UTC-forcing initialiser — called once regardless of how many
/// tests run in parallel within this binary.  Replaces the per-call
/// `unsafe { std::env::set_var(…) }` pattern which was not thread-safe.
static INIT_UTC: std::sync::Once = std::sync::Once::new();
fn force_utc_once() {
    INIT_UTC.call_once(ui::force_chart_utc_for_tests);
}

/// Legacy M1-B helper for the two pre-existing stable baselines that
/// used the M1-B PoC `("typical", 1280×720)` viewport convention. These
/// baselines are kept byte-identical per R-NR.1 — they are NOT renamed
/// or regenerated by the viewport-matrix expansion.
///
/// Used only by `strategies_ready_renders_clean` and `chart_screen_renders_clean`
/// legacy tests which act as regression guards on the old baselines.
fn run_panel_slot_legacy(panel_name: &str, slot_name: &str, cockpit: ui::Cockpit) {
    // Thread-safe UTC init via AtomicBool (replaces the old unsafe set_var).
    force_utc_once();

    // M1-B PoC slot — "typical" maps to (1280, 720) in the legacy convention.
    let (w, h, scale): (u32, u32, f32) = match slot_name {
        "typical" => (1280, 720, 1.0),
        other => panic!("run_panel_slot_legacy only supports 'typical'; got: {other}"),
    };

    let program = program_from_cockpit(cockpit);
    let theme = iced::Theme::Dark;

    let screenshot = iced_test::screenshot(&program, &theme, (w, h), scale, Duration::ZERO);

    let baseline = format!(
        "{}/tests/visual-baselines/render_snapshots/{panel_name}_dark_{slot_name}.png",
        env!("CARGO_MANIFEST_DIR")
    );
    let test_name = format!("{panel_name}_dark_{slot_name}");

    matches_screenshot(&screenshot, &baseline, &test_name).unwrap_or_else(|err| {
        panic!(
            "render-snapshot mismatch for `{panel_name}` slot `{slot_name}`:\n{err}\n\n\
             Review the baseline / actual / diff triple, then either:\n  \
             (a) accept the change: delete the baseline + rerun (helper auto-rewrites), or\n  \
             (b) reject the change: fix the producing widget code."
        )
    });
}

// ─── PoC: positions_ready ───────────────────────────────────────────────

// Per architect T-M1-B-2 acceptance criteria: the PoC fixture is
// `ui::fixtures::fake_cockpit_ready()` (positions in `Ready` state with
// the three-position fixture set). Rendering the full cockpit shell
// — not just the positions panel in isolation — keeps the harness
// congruent with `visual_snapshots.rs` and matches what an operator
// sees when they boot the fixtures cockpit.

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn positions_ready_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "positions_ready",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn positions_ready_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "positions_ready",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn positions_ready_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "positions_ready",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

// ─── Bulk migration tier (T-M1-B-3) ────────────────────────────────────
//
// Each panel surface gets render-snapshot tests at all three viewport
// slots. The 5 non-deterministic shell-composition tests inherit the
// `#[ignore]` decorator per D-VPM-3.

// NOTE on two-run determinism for shell-composition tests
// -------------------------------------------------------
//
// The five test groups below — `agent_feed_ready`, `kpi_strip_ready`,
// `pnl_panel_ready`, `positions_ready`, `focus_ring_baseline` — render
// the full cockpit shell (sidebar + screen body + status bar) via the
// home-screen `Cockpit` fixture, which carries surfaces with
// time-varying content under the default `iced_test::screenshot`
// timing (e.g. `iced_aw::Spinner` animations on Loading panels,
// status-bar uptime text). Two consecutive runs on the same fixture
// produce byte-level pixel diffs even with `Duration::ZERO`.
//
// These tests are marked `#[ignore]` so they do NOT block
// `cargo test -p ui`. The orchestrator runs them on a live capture
// host with the operator-approved baseline workflow:
//
//   cargo test -p ui --test render_snapshots -- --ignored
//
// The two stable groups — `strategies_ready` and `chart_screen` —
// DO satisfy the two-run determinism gate today and are NOT ignored.

#[test]
#[ignore = "shell composition has time-varying surfaces (spinner animation, uptime text); orchestrator runs via --ignored after fixture-deterministic-hook follow-up lands"]
fn agent_feed_ready_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "agent_feed_ready",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready_with_three_fills()),
    );
}

#[test]
#[ignore = "shell composition has time-varying surfaces (spinner animation, uptime text); orchestrator runs via --ignored after fixture-deterministic-hook follow-up lands"]
fn agent_feed_ready_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "agent_feed_ready",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready_with_three_fills()),
    );
}

#[test]
#[ignore = "shell composition has time-varying surfaces (spinner animation, uptime text); orchestrator runs via --ignored after fixture-deterministic-hook follow-up lands"]
fn agent_feed_ready_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "agent_feed_ready",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready_with_three_fills()),
    );
}

// strategies_ready — stable, no #[ignore]
#[test]
fn strategies_ready_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "strategies_ready",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_v15a_pairs_steady_state()),
    );
}

#[test]
fn strategies_ready_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "strategies_ready",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_v15a_pairs_steady_state()),
    );
}

#[test]
fn strategies_ready_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "strategies_ready",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_v15a_pairs_steady_state()),
    );
}

// Legacy M1-B baseline for strategies_ready at 1280×720 "typical" — kept byte-identical.
// This is the bootstrap anchor; the new matrix expansion writes parallel files.
#[test]
fn strategies_ready_renders_clean() {
    let cockpit = ui::fixtures::fake_cockpit_v15a_pairs_steady_state();
    run_panel_slot_legacy("strategies_ready", "typical", cockpit);
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn kpi_strip_ready_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "kpi_strip_ready",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn kpi_strip_ready_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "kpi_strip_ready",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn kpi_strip_ready_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "kpi_strip_ready",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn pnl_panel_ready_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "pnl_panel_ready",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn pnl_panel_ready_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "pnl_panel_ready",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn pnl_panel_ready_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "pnl_panel_ready",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

// chart_screen — stable, no #[ignore]
#[test]
fn chart_screen_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "chart_screen",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(fixtures::charts_screen_with_hovered_marker()),
    );
}

#[test]
fn chart_screen_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "chart_screen",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(fixtures::charts_screen_with_hovered_marker()),
    );
}

#[test]
fn chart_screen_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "chart_screen",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(fixtures::charts_screen_with_hovered_marker()),
    );
}

// Legacy M1-B baseline for chart_screen at 1280×720 "typical" — kept byte-identical.
#[test]
fn chart_screen_renders_clean() {
    let cockpit = fixtures::charts_screen_with_hovered_marker();
    run_panel_slot_legacy("chart_screen", "typical", cockpit);
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn focus_ring_baseline_renders_clean__floor() {
    viewport_matrix::snapshot_widget_at_slot(
        "focus_ring_baseline",
        "floor",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn focus_ring_baseline_renders_clean__typical() {
    viewport_matrix::snapshot_widget_at_slot(
        "focus_ring_baseline",
        "typical",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

#[test]
#[ignore = "shell composition non-determinism — see note above `agent_feed_ready_renders_clean`"]
fn focus_ring_baseline_renders_clean__operator() {
    viewport_matrix::snapshot_widget_at_slot(
        "focus_ring_baseline",
        "operator",
        Some("render_snapshots"),
        || program_from_cockpit(ui::fixtures::fake_cockpit_ready()),
    );
}

// Note on journal_transaction_modal coverage:
// The modal renders only when `cockpit.journal_modal` is in `Open`
// state. The fixtures crate does not currently expose a builder for
// this state (the modal opens via a click in the audit screen). The
// developer surfaces this in `[open_questions].items` so the
// orchestrator can either (a) add `fake_cockpit_with_journal_modal()`
// to `ui::fixtures` in a follow-up tick, or (b) author the fixture
// inline in `tests/fixtures/mod.rs`. Option (b) keeps the production
// fixture surface narrow per `ui-test-harness-bootstrap` Q6 lock.
// The journal_transaction_modal proptest in `layout_invariants.rs`
// stands in as the M1-B-3 acceptance criterion for this surface
// until the orchestrator routes the fixture decision.
